version: '2'
services:
  web:
    user: root
    build: .
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    container_name: loopback-node-red-example
    volumes:
       - "./data:/data"
    depends_on:
      - mosquitto
      - mongo
    links:
      - mosquitto
      - mongo

  mosquitto:
    image: "eclipse-mosquitto:1.4.8"
    container_name: mosquitto-server
    ports:
      - "1883:1883"
      - "9001:9001"

  mongo:
    image: "mongo:3.4"
    container_name: mongo-db
    ports:
      - "27017:27017"
