version: '2'
services:
  web:
    user: node-red
    build: .
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    container_name: loopback-node-red-example
    depends_on:
      - mosquitto
    links:
      - mosquitto
  mosquitto:
    image: "eclipse-mosquitto:1.4.8"
    container_name: mosquitto-server
    ports:
      - "1883:1883"
      - "9001:9001"